# Generated by Django 5.2 on 2025-04-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppCitas', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.pacientes'),
        ),
        migrations.AddField(
            model_name='citas',
            name='horario_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCitas.horariosmedico'),
        ),
        migrations.AddField(
            model_name='serviciosmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctores'),
        ),
        migrations.AddField(
            model_name='serviciosmedico',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCitas.servicios'),
        ),
        migrations.AddField(
            model_name='horariosmedico',
            name='servicio_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCitas.serviciosmedico'),
        ),
    ]
